spring:
  application:
    name: capitall
  datasource:
    url: jdbc:h2:file:./data/capitalldb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
    com.capitall: INFO

capitall:
  encryption:
    secret-key: "qV_sUpEr_sEcReT_kEy_fOr_aEs_256!" # 32 bytes key for AES-256
