spring:
  application:
    name: capitall
  datasource:
    url: jdbc:h2:mem:capitalldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

capitall:
  encryption:
    secret-key: "qV_sUpEr_sEcReT_kEy_fOr_aEs_256!" # 32 bytes key for AES-256
